name: Deploy Next.js to GitHub Pages

on:
    push:
        tags:
            - '*'
    release:
        types: [published]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Create .env file
              run: |
                  echo NEXT_PUBLIC_MANIFEST_VERSION=$(sha1sum public/data/stigs/manifest.json | awk '{print $1}') >> .env

            - name: Retrieve the cached "node_modules" directory (if present)
              uses: actions/cache@v4
              id: node-cache
              with:
                  path: ./node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}-v1

            - name: Install dependencies
              run: npm install
              if: steps.node-cache.outputs.cache-hit != 'true'

            - name: Build App
              env:
                  NEXT_PUBLIC_API_URL: 'http://localhost:3000'
              run: |
                  npm run dev &
                  PID=$!
                  sleep 5

                  # Build against dev instance
                  npm run build

                  # Fix static files
                  for file in $(grep -l -R 'http://localhost:3000'); do 
                    sed -i -e 's|http://localhost:3000|https://stigui.neal.codes|g' $file
                  done

                  # Stop dev server
                  kill $PID

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  cname: stigui.neal.codes
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./out # This is the default output directory for `next export`
