name: Test

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Create .env file
              run: |
                  echo NEXT_PUBLIC_MANIFEST_VERSION=$(sha1sum public/data/stigs/manifest.json | awk '{print $1}') >> .env

            - name: Retrieve the cached "node_modules" directory (if present)
              uses: actions/cache@v4
              id: node-cache
              with:
                  path: ./node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}-v1

            - name: Install dependencies
              run: npm install
              if: steps.node-cache.outputs.cache-hit != 'true'

            - run: npm run test
